// Supabase access for the docgen service (service-role key — server-side only).
// Node < 22 has no global WebSocket; supabase-js realtime requires one at init even though
// we never use realtime here. Polyfill it with `ws` so createClient() doesn't crash.
if (!globalThis.WebSocket) { try { globalThis.WebSocket = require('ws'); } catch (e) { /* ignore */ } }
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;
const BUCKET = process.env.DOCS_BUCKET || 'documents';
// Anon key is public-safe (it ships in the browser bundle). Used only to validate user JWTs
// via GoTrue — the service-role key is rejected by the auth endpoint for that call.
const ANON_KEY = process.env.SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyenVpdm95YWVqaHFmaXRmbnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3Mzc0NzIsImV4cCI6MjA5NTMxMzQ3Mn0.5FARwWmJczlvU1pROumim8oHZRTqnMofWbcMUfrVVPo';

if (!SUPABASE_URL || !SERVICE_ROLE) {
  console.warn('[docgen] SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set — DB calls will fail.');
}

const supabase = createClient(SUPABASE_URL || 'http://localhost', SERVICE_ROLE || 'anon', {
  auth: { persistSession: false, autoRefreshToken: false },
});

// Separate client keyed with the anon key, used only to validate end-user JWTs.
const supabaseAuth = createClient(SUPABASE_URL || 'http://localhost', ANON_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

async function getJob(jobId) {
  const { data, error } = await supabase.from('document_jobs').select('*').eq('id', jobId).single();
  if (error) throw new Error('Job not found: ' + error.message);
  return data;
}

async function getBrandKit(tenantId) {
  const { data } = await supabase.from('brand_kits').select('*').eq('tenant_id', tenantId).maybeSingle();
  // Sensible WE-house defaults if the client has no kit yet.
  return data || { primary_color: '0C1C3B', accent_color: '4393A5', dark_color: '333333', light_color: 'FFFFFF', logo_url: null };
}

async function updateJob(jobId, patch) {
  const { error } = await supabase.from('document_jobs')
    .update({ ...patch, updated_at: new Date().toISOString() }).eq('id', jobId);
  if (error) throw new Error('Job update failed: ' + error.message);
}

// Upload a buffer to Storage and return its storage path (signed URLs are generated by the app on demand).
async function uploadFile(path, buffer, contentType) {
  const { error } = await supabase.storage.from(BUCKET).upload(path, buffer, { contentType, upsert: true });
  if (error) throw new Error('Upload failed (' + path + '): ' + error.message);
  return path;
}

// Optionally download the client logo so it can be embedded on the cover.
async function downloadLogo(logoUrl) {
  if (!logoUrl) return null;
  try {
    // logoUrl may be a storage path inside the bucket, or a full URL.
    if (/^https?:\/\//.test(logoUrl)) {
      const res = await fetch(logoUrl);
      if (!res.ok) return null;
      return Buffer.from(await res.arrayBuffer());
    }
    const { data, error } = await supabase.storage.from(BUCKET).download(logoUrl);
    if (error || !data) return null;
    return Buffer.from(await data.arrayBuffer());
  } catch (e) {
    return null;
  }
}

module.exports = { supabase, supabaseAuth, getJob, getBrandKit, updateJob, uploadFile, downloadLogo, BUCKET };
